fix: Python packaging error message was missing (#116)
Instead of returning the actual error message to the custom resource, we returned:

```
Internal error: 'CommandError' object has no attribute 'message'
```

Fixes #115